# Generated by Django 4.2.30 on 2026-04-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["item"], name="littleLemon_item_34c7a2_idx")
                ],
            },
        ),
    ]
