# Generated by Django 6.0.4 on 2026-04-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "littleLemonDRF",
            "0002_category_remove_menu_littlelemon_item_34c7a2_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu",
            old_name="catgeory",
            new_name="category",
        ),
    ]
