# Generated by Django 6.0.4 on 2026-04-10 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("littleLemonDRF", "0003_rename_catgeory_menu_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Menu",
        ),
    ]
